{
 "title": "URL",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Total requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(url_shortener_http_server_requests_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total requests p/sec",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(url_shortener_http_server_requests_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "URLs criadas",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(url_shortener_http_server_urls_created_total[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU (%)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(url_shortener_process_cpu_seconds_total[5m]) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "url_shortener_go_goroutines", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Uso de memória (mb)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "url_shortener_go_memstats_heap_alloc_bytes / 1024 / 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Traces - Redirect",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "targets": [
    { "limit": 25, "operation": "redirect-handler", "service": "url-shortener" }
   ]
  },
  {
   "title": "Traces - Create",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "targets": [
    { "limit": 25, "operation": "create-handler", "service": "url-shortener" }
   ]
  }
 ]
}